### ISSUE TITLE
element-ui 的组件 tooltip无法使用

### ISSUE THREAD

**Issue by 18610509683** [underfin/vite-plugin-vue2#215] opened 2023-02-10 02:46 UTC
element-ui 的组件 tooltip无法使用，貌似样式都没加载出来

**Comment by antfu** [comment] 2023-02-16 23:08
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed as completed by antfu** 2023-02-16 23:08 UTC
